export const API_KEYS = {
  GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
  ANDROID_GOOGLE_SERVICES_BASE64: process.env.ANDROID_GOOGLE_SERVICES_BASE64,
  IOS_GOOGLE_SERVICES_BASE64: process.env.IOS_GOOGLE_SERVICES_BASE64,
  API_URL: process.env.EXPO_PUBLIC_API_URL,
};

export const NOTIFICATION_KEYS = {
  REMINDER_ENABLED: "reminderEnabled",
  REMINDER_TIME: "reminderTime",
  NOTIFICATION_PROMPT_KEY: "hasPromptedForNotifications",
};

export const THEME_KEYS = {
  THEME: "theme",
};
