name: Schedule Node.js Script

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
    - cron: "0 0 * * MON" # Runs every Monday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: node index.js --manual-reset
