name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

# Add permissions block to limit GitHub token scope
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore backend/Lithuaningo.API.sln

      - name: Build
        run: dotnet build backend/Lithuaningo.API.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test backend/Lithuaningo.API.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish backend/Lithuaningo.API/Lithuaningo.API.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lithuaningo-api"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
